---
#     __             __                                  __
# .--|  .-----.-----|  .-----.--.--.--------.-----.-----|  |-.-----.
# |  _  |  -__|  _  |  |  _  |  |  |        |  -__|     |   _|__ --|
# |_____|_____|   __|__|_____|___  |__|__|__|_____|__|__|____|_____|
#             |__|           |_____|

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Blackboxf1-realtime
  namespace: Blackboxf1
  labels:
    app: Blackboxf1-realtime
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Blackboxf1-realtime
  template:
    metadata:
      labels:
        app: Blackboxf1-realtime
    spec:
      containers:
        - name: realtime
          image: ghcr.io/FocusFV/Blackboxf1-realtime:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          env:
            - name: RUST_LOG
              value: "realtime=debug"
            - name: ADDRESS
              value: "0.0.0.0:80"
            - name: ORIGIN
              value: "https://https://Blackboxf1.vercel.app/"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Blackboxf1-api
  namespace: Blackboxf1
  labels:
    app: Blackboxf1-api
spec:
  selector:
    matchLabels:
      app: Blackboxf1-api
  template:
    metadata:
      labels:
        app: Blackboxf1-api
    spec:
      containers:
        - name: api
          image: ghcr.io/FocusFV/Blackboxf1-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "64Mi"
              cpu: "20m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 80
          readinessProbe:
            httpGet:
              path: /api/health
              port: 80
          env:
            - name: ORIGIN
              value: "https://https://Blackboxf1.vercel.app/"
            - name: API_ADDRESS
              value: "0.0.0.0:80"
            - name: RUST_LOG
              value: "api=debug"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Blackboxf1-web
  namespace: Blackboxf1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Blackboxf1-web
  template:
    metadata:
      labels:
        app: Blackboxf1-web
    spec:
      containers:
        - name: web
          image: ghcr.io/FocusFV/Blackboxf1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 256Mi
              cpu: 500m
            limits:
              memory: 1Gi
              cpu: 1000m
          env:
            - name: NEXT_PUBLIC_LIVE_URL
              value: "https://rt-api.https://Blackboxf1.vercel.app/"
            - name: API_URL
              value: "https://api.https://Blackboxf1.vercel.app/"
            - name: DISABLE_IFRAME
              value: "1"
