---
#                         __
# .-----.-----.----.--.--|__.----.-----.-----.
# |__ --|  -__|   _|  |  |  |  __|  -__|__ --|
# |_____|_____|__|  \___/|__|____|_____|_____|

apiVersion: v1
kind: Service
metadata:
  name: Blackboxf1-web
  namespace: Blackboxf1
  labels:
    app: Blackboxf1-web
spec:
  ports:
    - name: Blackboxf1-web
      port: 3000
      targetPort: 3000
  selector:
    app: Blackboxf1-web

---
apiVersion: v1
kind: Service
metadata:
  name: Blackboxf1-realtime
  namespace: Blackboxf1
  labels:
    app: Blackboxf1-realtime
spec:
  ports:
    - name: Blackboxf1-realtime
      port: 80
      targetPort: 80
  selector:
    app: Blackboxf1-realtime

---
apiVersion: v1
kind: Service
metadata:
  name: Blackboxf1-api
  namespace: Blackboxf1
  labels:
    app: Blackboxf1-api
spec:
  ports:
    - name: Blackboxf1-api
      port: 80
      targetPort: 80
  selector:
    app: Blackboxf1-api
