FROM rust:1.80-slim AS builder
WORKDIR /app
COPY . .
RUN cargo build --release --bin simulator

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/target/release/simulator /app/simulator
CMD ["./simulator"]